FROM rust:1.91 as builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/shorty /usr/local/bin/shorty
ENV RUST_LOG=info
CMD ["/usr/local/bin/shorty", "--worker"]
